# -*- mode: ruby -*-
# vi: set ft=ruby :

LOGIN = "adelaloy"
SERVER_NAME = "#{LOGIN}S"
WORKER_NAME = "#{LOGIN}SW"
SERVER_IP = "192.168.56.110"
WORKER_IP = "192.168.56.111"

MAC_ARM64 = RUBY_PLATFORM.include?("darwin") &&
            `sysctl -n hw.optional.arm64 2>/dev/null`.strip == "1"

HAS_LIBVIRT = Vagrant.has_plugin?("vagrant-libvirt")

if HAS_LIBVIRT
  BOX = "generic/ubuntu2204"
  BOX_VERSION = nil
elsif MAC_ARM64
  BOX = "bento/ubuntu-22.04"
  BOX_VERSION = "202502.21.0"
else
  BOX = "generic/ubuntu2204"
  BOX_VERSION = nil
end

Vagrant.configure("2") do |config|
  config.vm.box = BOX
  config.vm.box_version = BOX_VERSION if BOX_VERSION
  config.vm.box_architecture = "arm64" if MAC_ARM64 && !HAS_LIBVIRT

  config.vm.define SERVER_NAME do |server|
    server.vm.hostname = SERVER_NAME
    server.vm.network "private_network", ip: SERVER_IP

    server.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", SERVER_NAME]
      v.memory = 1024
      v.cpus = 1
    end

    server.vm.provider "libvirt" do |v|
      v.memory = 1024
      v.cpus = 1
      v.driver = "qemu"
      v.machine_type = "virt"
      v.machine_arch = "aarch64"
      v.cpu_mode = "custom"
      v.cpu_model = "cortex-a72"
      v.loader = "/usr/share/AAVMF/AAVMF_CODE.fd"
      v.nvram = "/usr/share/AAVMF/AAVMF_VARS.fd"
    end

    server.vm.synced_folder ".", "/vagrant", type: "rsync"
    server.vm.provision "shell", path: "scripts/server.sh", args: [SERVER_IP]
  end

  config.vm.define WORKER_NAME do |worker|
    worker.vm.hostname = WORKER_NAME
    worker.vm.network "private_network", ip: WORKER_IP

    worker.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", WORKER_NAME]
      v.memory = 1024
      v.cpus = 1
    end

    worker.vm.provider "libvirt" do |v|
      v.memory = 1024
      v.cpus = 1
      v.driver = "qemu"
      v.machine_type = "virt"
      v.machine_arch = "aarch64"
      v.cpu_mode = "custom"
      v.cpu_model = "cortex-a72"
      v.loader = "/usr/share/AAVMF/AAVMF_CODE.fd"
      v.nvram = "/usr/share/AAVMF/AAVMF_VARS.fd"
    end

    worker.vm.synced_folder ".", "/vagrant", type: "rsync"
    worker.vm.provision "shell", path: "scripts/worker.sh", args: [SERVER_IP, WORKER_IP]
  end
end
