# -*- mode: ruby -*-
# vi: set ft=ruby :

# Part 1 — subject: 2 VMs, Vagrant + VirtualBox, K3s server + agent.
LOGIN = "adelaloy"
SERVER_NAME = "#{LOGIN}S"
WORKER_NAME = "#{LOGIN}SW"
SERVER_IP = "192.168.56.110"
WORKER_IP = "192.168.56.111"

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"

  config.vm.define SERVER_NAME do |server|
    server.vm.hostname = SERVER_NAME
    server.vm.network "private_network", ip: SERVER_IP
    server.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", SERVER_NAME]
      v.memory = 1024
      v.cpus = 1
    end
    server.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    server.vm.provision "shell", path: "scripts/server.sh", args: [SERVER_IP]
  end

  config.vm.define WORKER_NAME do |worker|
    worker.vm.hostname = WORKER_NAME
    worker.vm.network "private_network", ip: WORKER_IP
    worker.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", WORKER_NAME]
      v.memory = 1024
      v.cpus = 1
    end
    worker.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    worker.vm.provision "shell", path: "scripts/worker.sh", args: [SERVER_IP, WORKER_IP]
  end
end
